
$wppPath  = "https://wa.me/5531992395859"
$wppPhone = "https://wa.me/5531993728984"
$svg22 = '<svg width="22" height="22" viewBox="0 0 24 24" fill="currentColor"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/></svg>'

$cities = @(
  @{ slug="uberlandia"; name="Uberlandia_acc"; regiao="Triangulo Mineiro"
     desc="Protecao veicular em Uberlandia com cobertura completa sem carencia e sem burocracia. Helios atende todos os bairros do Triangulo Mineiro. Cotacao gratis."
     heroSub="No coracao do Triangulo Mineiro, a Helios oferece cobertura completa pelo menor preco. Sem carencia, sem vistoria, ativo no mesmo dia."
     urgency="Uberlandia esta entre as cidades com maior indice de roubos de veiculos do interior de MG."
     bairros=@("Tibery","Tabajaras","Shopping Park","Saraiva","Tubalina","Mansour","Morada da Colina","Santa Maria","Custodio Pereira","Lidice","Jardim Karaiba","Segismundo Pereira")
     t1i="JP"; t1n="Joao P."; t1b="Tibery, Uberlandia"; t1t="Cotei pelo WhatsApp em 10 minutos e no mesmo dia ja estava com meu carro protegido. Preco muito abaixo do seguro tradicional. Recomendo!"
     t2i="CR"; t2n="Carla R."; t2b="Saraiva, Uberlandia"; t2t="Tive um sinistro e a Helios resolveu tudo rapidamente. O suporte foi excelente do inicio ao fim. Nao troco mais por nenhum seguro convencional."
     t3i="PT"; t3n="Paulo T."; t3b="Mansour, Uberlandia"; t3t="Processo 100% digital, sem burocracia. Segurei meu veiculo em 15 minutos pelo celular. A assistencia 24h ja me salvou na estrada."
     faqQ="A Helios atende motoristas de aplicativo em Uberlandia?"; faqA="Sim! Oferecemos planos especificos para motoristas de Uber, 99 e iFood em Uberlandia, com cobertura adaptada para uso profissional do veiculo."
  },
  @{ slug="sete-lagoas"; name="Sete Lagoas"; regiao="regiao de Sete Lagoas"
     desc="Protecao veicular em Sete Lagoas sem carencia e sem vistoria. Helios protege seu veiculo na Grande BH norte com cobertura completa e assistencia 24h."
     heroSub="A cidade das nascentes merece a melhor protecao para o seu veiculo. Ative sua cobertura hoje, sem burocracia e sem carencia."
     urgency="Sete Lagoas registra crescimento nos indices de furtos de veiculos na regiao metropolitana norte de BH."
     bairros=@("Varzea","Sao Joao","N. Sra. das Gracas","Industrial","Alto Paraiso","Jardim Paulista","Bom Jesus","Nossa Sra. das Dores","Barreiro","Xangri-la","Eldorado","Sao Geraldo")
     t1i="LM"; t1n="Lucas M."; t1b="Varzea, Sete Lagoas"; t1t="Fui indicado por um amigo e nao me arrependo. Processo simples, rapido e sem papelada. Ja estou protegido ha 6 meses e super satisfeito."
     t2i="PG"; t2n="Patricia G."; t2b="Jardim Paulista, Sete Lagoas"; t2t="Minha moto foi roubada e a Helios cumpriu tudo o que prometeu. Atendimento humanizado e indenizacao rapida. Nota 10!"
     t3i="RN"; t3n="Roberto N."; t3b="Industrial, Sete Lagoas"; t3t="Pago menos da metade do que pagava no seguro e tenho a mesma cobertura. Sem carencia foi o principal fator da minha escolha."
     faqQ="A Helios cobre veiculos usados em Sete Lagoas?"; faqA="Sim! Protegemos veiculos de diversas faixas de ano em Sete Lagoas. Fale conosco pelo WhatsApp e receba uma cotacao personalizada para o seu veiculo."
  },
  @{ slug="teofilo-otoni"; name="Teofilo Otoni"; regiao="Vale do Mucuri"
     desc="Protecao veicular em Teofilo Otoni e Vale do Mucuri. Helios oferece cobertura completa contra roubo, furto e colisao sem carencia. Cotacao gratis pelo WhatsApp."
     heroSub="No Vale do Mucuri, a Helios garante protecao completa para o seu veiculo. Processo 100% digital, ativo no mesmo dia da adesao."
     urgency="Teofilo Otoni concentra boa parte dos registros de roubo de veiculos do Nordeste de Minas Gerais."
     bairros=@("Plato","Santo Antonio","Santa Clara","Boa Vista","Fatima","Jardim Primavera","Bela Vista","Altino Barbosa","Kennedy","Panorama","Alvorada","Sao Cristovao")
     t1i="AS"; t1n="Andre S."; t1b="Plato, Teofilo Otoni"; t1t="Indicado por um colega de trabalho. Contratei pelo celular em menos de 20 minutos. Atendimento rapido e preco justo. Vale muito a pena!"
     t2i="JM"; t2n="Juliana M."; t2b="Santo Antonio, Teofilo Otoni"; t2t="Tive um problema com meu carro na estrada e o guincho chegou em tempo recorde. A assistencia 24h funciona de verdade. Muito satisfeita!"
     t3i="CB"; t3n="Carlos B."; t3b="Fatima, Teofilo Otoni"; t3t="Nao precisei fazer vistoria e ja sai protegido no mesmo dia. O preco e bem mais acessivel do que o seguro que eu tinha antes. Recomendo!"
     faqQ="A protecao da Helios cobre toda a regiao de Teofilo Otoni?"; faqA="Sim! Atendemos Teofilo Otoni e toda a regiao do Vale do Mucuri. A cobertura e valida em todo o territorio nacional, incluindo viagens e deslocamentos."
  },
  @{ slug="patos-de-minas"; name="Patos de Minas"; regiao="Alto Paranaiba"
     desc="Protecao veicular em Patos de Minas sem carencia. Helios protege seu veiculo no Alto Paranaiba com cobertura completa e assistencia 24h. Faca sua cotacao gratis."
     heroSub="No Alto Paranaiba, a Helios e a escolha certa para proteger seu veiculo com custo acessivel e ativacao no mesmo dia."
     urgency="Patos de Minas registra aumento no numero de sinistros veiculares na regiao do Alto Paranaiba."
     bairros=@("Jardim Esperanca","Maracana","Planalto","Sao Sebastiao","Rio Paranaiba","Santa Terezinha","Caicara","Bela Vista","Vilage","Jardim Sao Paulo","Sao Lucas","Padre Eustachio")
     t1i="DF"; t1n="Diego F."; t1b="Maracana, Patos de Minas"; t1t="Processo bem simples e rapido. Fiz tudo pelo celular e em menos de meia hora ja estava com a protecao ativa. Otimo custo-beneficio!"
     t2i="RA"; t2n="Renata A."; t2b="Planalto, Patos de Minas"; t2t="Meu marido ja era cliente e me indicou. Agora os dois carros da familia estao protegidos pela Helios. Atendimento excelente sempre que precisei."
     t3i="SC"; t3n="Silvio C."; t3b="Sao Sebastiao, Patos de Minas"; t3t="Sem carencia foi decisivo para eu contratar. Pago menos da metade do seguro e tenho cobertura completa. A assistencia 24h ja funcionou duas vezes."
     faqQ="A Helios atende municipios proximos a Patos de Minas?"; faqA="Sim! Alem de Patos de Minas, atendemos toda a regiao do Alto Paranaiba, incluindo Lagoa Formosa, Presidente Olegario e municipios vizinhos. A cobertura e valida em todo o Brasil."
  },
  @{ slug="pouso-alegre"; name="Pouso Alegre"; regiao="Sul de Minas"
     desc="Protecao veicular em Pouso Alegre sem carencia e sem vistoria. Helios protege seu veiculo no Sul de Minas com cobertura completa. Cotacao gratis pelo WhatsApp."
     heroSub="No Sul de Minas Gerais, a Helios oferece protecao completa para o seu veiculo com preco acessivel e ativacao imediata."
     urgency="Pouso Alegre registra crescimento nos indices de furto de veiculos no Sul de Minas."
     bairros=@("Paissandu","Nova Suica","Bortolan","Santa Luzia","Aeroporto","Aracy","Jd. das Oliveiras","Sao Joao","Trevo","Vila Rica","Santa Rosa","Campos Eliseos")
     t1i="TV"; t1n="Thiago V."; t1b="Paissandu, Pouso Alegre"; t1t="Fiz a cotacao e no mesmo dia ja estava protegido. Sem burocracia, sem vistoria. Atendimento pelo WhatsApp muito agil e prestativo."
     t2i="NR"; t2n="Natalia R."; t2b="Bortolan, Pouso Alegre"; t2t="Meu carro foi danificado em uma colisao e a Helios cuidou de tudo. Processo mais simples do que eu imaginava. Super recomendo!"
     t3i="GM"; t3n="Gustavo M."; t3b="Nova Suica, Pouso Alegre"; t3t="Economizo R$150 por mes em relacao ao seguro antigo com a mesma cobertura. Sem carencia foi o que me convenceu a contratar na hora."
     faqQ="A protecao da Helios e valida para quem viaja de Pouso Alegre para Sao Paulo?"; faqA="Sim! A cobertura e valida em todo o Brasil. Seja nas viagens pela Fernao Dias ou em qualquer outro trajeto, voce esta protegido 24h por dia."
  },
  @{ slug="varginha"; name="Varginha"; regiao="Sul de Minas"
     desc="Protecao veicular em Varginha sem carencia e sem burocracia. Helios cobre roubo, furto e colisao no Sul de Minas com assistencia 24h. Cotacao gratis agora."
     heroSub="Na capital do cafe do Sul de Minas, a Helios protege seu veiculo com cobertura completa, ativacao no mesmo dia e preco que cabe no bolso."
     urgency="Varginha registra aumento nos registros de sinistros veiculares na regiao do Sul de Minas."
     bairros=@("Jardim Andere","Sao Tome","Bela Vista","Santa Ines","Jaragua","Novo Horizonte","Monte Belo","Esplanada","Colonia","Vila Pinto","Fatima","Sao Judas")
     t1i="FS"; t1n="Felipe S."; t1b="Jaragua, Varginha"; t1t="Cotei pelo WhatsApp e em 15 minutos ja tinha o preco. No mesmo dia assinei tudo pelo celular. Muito mais facil do que qualquer seguro que ja contratei."
     t2i="AT"; t2n="Aline T."; t2b="Sao Tome, Varginha"; t2t="Excelente atendimento! Quando precisei acionar tive uma resposta rapida e sem estresse. Vale muito a pena para quem quer protecao real com preco justo."
     t3i="ML"; t3n="Marcio L."; t3b="Bela Vista, Varginha"; t3t="Sem carencia foi o ponto decisivo. Ja estava desprotegido ha meses com medo do custo. A Helios me surpreendeu positivamente em tudo."
     faqQ="A Helios atende frota de veiculos em Varginha?"; faqA="Sim! Atendemos veiculos de passeio, SUVs, motos e tambem consultas para frotas em Varginha e regiao Sul de Minas. Entre em contato para uma proposta personalizada."
  },
  @{ slug="barbacena"; name="Barbacena"; regiao="Campo das Vertentes"
     desc="Protecao veicular em Barbacena e Campo das Vertentes. Helios oferece cobertura completa sem carencia e sem vistoria. Cotacao gratuita pelo WhatsApp em minutos."
     heroSub="Na Cidade das Rosas, a Helios cuida do que mais importa: a protecao do seu veiculo, com ativacao imediata e preco acessivel."
     urgency="Barbacena registra indices crescentes de furto de veiculos na regiao do Campo das Vertentes."
     bairros=@("Sao Sebastiao","Jardim das Rosas","Nova Vista","Alterosa","Pio XII","Lourdes","Padre Dehon","Santa Terezinha","Bom Jesus","Paraiso","Moreira","Junco")
     t1i="ER"; t1n="Eduardo R."; t1b="Sao Sebastiao, Barbacena"; t1t="Processo rapidissimo. Fiz tudo pelo WhatsApp sem sair de casa. No mesmo dia ja estava com o carro protegido. Muito melhor que o seguro!"
     t2i="VM"; t2n="Vanessa M."; t2b="Alterosa, Barbacena"; t2t="Nunca pensei que contratar protecao veicular fosse tao simples. Sem vistoria, sem papelada. Recomendo para todo mundo em Barbacena!"
     t3i="RF"; t3n="Ricardo F."; t3b="Nova Vista, Barbacena"; t3t="A assistencia 24h ja me ajudou com pane seca na estrada para BH. Atendimento impecavel e rapido. Vale cada centavo da mensalidade."
     faqQ="A Helios atende municipios proximos a Barbacena como Conselheiro Lafaiete?"; faqA="Sim! Atendemos Barbacena e toda a regiao do Campo das Vertentes, incluindo cidades vizinhas. Nossa cobertura e valida em todo o Brasil."
  },
  @{ slug="conselheiro-lafaiete"; name="Conselheiro Lafaiete"; regiao="Quadrilatero Ferrifero"
     desc="Protecao veicular em Conselheiro Lafaiete sem carencia. Helios protege seu veiculo no Quadrilatero Ferrifero com cobertura completa e assistencia 24h. Cotacao gratis."
     heroSub="No coracao do Quadrilatero Ferrifero, a Helios oferece protecao completa para o seu veiculo com ativacao no mesmo dia da adesao."
     urgency="Conselheiro Lafaiete registra aumento nos indices de roubo e furto de veiculos na regiao do Quadrilatero Ferrifero."
     bairros=@("Guanabara","Coqueiros","Nova Floresta","Esperanca","Bom Retiro","Vila Aparecida","Santo Antonio","Jardim dos Ipes","Morro do Engenho","Santa Cruz","Palmeiras","Sao Judas")
     t1i="BA"; t1n="Bruno A."; t1b="Guanabara, Cons. Lafaiete"; t1t="Indicado por um colega que ja era cliente. Processo simples e rapido pelo WhatsApp. Protecao ativa no mesmo dia, sem nenhuma burocracia!"
     t2i="SR"; t2n="Simone R."; t2b="Coqueiros, Cons. Lafaiete"; t2t="Tive um sinistro meses atras e fui muito bem atendida. O processo de indenizacao foi mais agil do que eu esperava. Recomendo de olhos fechados."
     t3i="HM"; t3n="Henrique M."; t3b="Nova Floresta, Cons. Lafaiete"; t3t="Economizo bastante em relacao ao seguro tradicional. Sem carencia e com carro reserva incluso. A assistencia 24h ja funcionou quando precisei."
     faqQ="A Helios cobre trajetos entre Conselheiro Lafaiete e Belo Horizonte?"; faqA="Sim! A cobertura e valida em todo o Brasil, incluindo o trajeto pela BR-040 entre Conselheiro Lafaiete e BH. Voce esta protegido em qualquer estrada ou cidade."
  },
  @{ slug="coronel-fabriciano"; name="Coronel Fabriciano"; regiao="Vale do Aco"
     desc="Protecao veicular em Coronel Fabriciano e Vale do Aco. Helios oferece cobertura completa sem carencia e sem vistoria. Cotacao gratis no WhatsApp em minutos."
     heroSub="No dinamico Vale do Aco, a Helios protege seu veiculo com cobertura completa, sem carencia e com ativacao imediata pelo celular."
     urgency="O Vale do Aco registra alto volume de sinistros veiculares, especialmente em Coronel Fabriciano e Ipatinga."
     bairros=@("Caladao","Industrial","Primavera","Nova Esperanca","Vale Verde","Boa Vista","Santa Cruz","Limoeiro","Centro","Novo Horizonte","Aparecida","Sao Judas")
     t1i="FC"; t1n="Fabio C."; t1b="Caladao, Coronel Fabriciano"; t1t="Trabalho na industria e sempre viajo entre cidades do Vale do Aco. A Helios me da tranquilidade em todos esses deslocamentos. Atendimento excelente!"
     t2i="CB"; t2n="Cristiane B."; t2b="Primavera, Coronel Fabriciano"; t2t="Nunca imaginei contratar protecao veicular tao facil. Tudo pelo WhatsApp, sem vistoria, sem papelada. Estou muito satisfeita com a cobertura!"
     t3i="LS"; t3n="Leandro S."; t3b="Industrial, Coronel Fabriciano"; t3t="Pago menos da metade do que pagava no seguro com a mesma cobertura. A assistencia 24h ja me ajudou duas vezes. Nao volto mais para o seguro tradicional."
     faqQ="A Helios atende toda a regiao do Vale do Aco?"; faqA="Sim! Alem de Coronel Fabriciano, atendemos Ipatinga, Timoteo, Santana do Paraiso e toda a regiao do Vale do Aco. Nossa cobertura e valida em todo o Brasil."
  },
  @{ slug="muriae"; name="Muriae_acc"; regiao="Zona da Mata"
     desc="Protecao veicular em Muriae e Zona da Mata mineira. Helios oferece cobertura completa sem carencia, sem vistoria e com assistencia 24h. Cotacao gratis pelo WhatsApp."
     heroSub="Na Zona da Mata de Minas Gerais, a Helios protege seu veiculo com cobertura completa, processo 100% digital e preco que surpreende."
     urgency="Muriae e a Zona da Mata registram crescimento nos indices de sinistros veiculares nos ultimos anos."
     bairros=@("Sao Judas","Santa Cruz","Jequitiba","Planalto","Novo Horizonte","Bom Pastor","Nossa Sra. de Fatima","Triangulo","Aeroporto","Sao Lourenco","Liberdade","Sao Jose")
     t1i="AM"; t1n="Adriano M."; t1b="Sao Judas, Muriae"; t1t="Fui indicado e nao me arrependi. Cotacao rapida, sem vistoria e protecao ativa no mesmo dia. Preco muito melhor que qualquer seguro da regiao!"
     t2i="PR"; t2n="Priscila R."; t2b="Santa Cruz, Muriae"; t2t="Quando meu carro foi batido, a Helios resolveu tudo com muita agilidade. Atendimento humano e eficiente do inicio ao fim. Super recomendo!"
     t3i="NT"; t3n="Nelson T."; t3b="Planalto, Muriae"; t3t="Sem carencia foi o que me convenceu. Agora tenho cobertura completa pagando muito menos. A assistencia 24h e real e funciona quando precisamos."
     faqQ="A Helios atende municipios da Zona da Mata proximos a Muriae?"; faqA="Sim! Atendemos Muriae e toda a Zona da Mata mineira, incluindo Leopoldina, Cataguases e municipios vizinhos. A cobertura e valida em todo o territorio nacional."
  }
)

# Mapa de acentuacao para nomes de cidades
$accMap = @{
  "Uberlandia_acc" = "Uberlândia"
  "Muriae_acc"     = "Muriaé"
}

$base = "C:\Users\SAMSUNG\Helios\novo-site"

foreach ($c in $cities) {
  $slug = $c.slug
  $name = if ($accMap.ContainsKey($c.name)) { $accMap[$c.name] } else { $c.name }
  $dir  = "$base\$slug"
  New-Item -ItemType Directory -Path $dir -Force | Out-Null

  $bairrosTags = ($c.bairros | ForEach-Object { "      <span class=`"bairro-tag`">$_</span>" }) -join "`r`n"

  $html  = "<!DOCTYPE html>`r`n"
  $html += "<html lang=`"pt-BR`">`r`n<head>`r`n"
  $html += "  <meta charset=`"UTF-8`">`r`n"
  $html += "  <meta name=`"viewport`" content=`"width=device-width, initial-scale=1.0`">`r`n"
  $html += "  <title>Protecao Veicular em $name sem Carencia | Helios</title>`r`n"
  $html += "  <meta name=`"description`" content=`"$($c.desc)`">`r`n"
  $html += "  <link rel=`"canonical`" href=`"https://heliosprotecaoveicular.com.br/$slug/`">`r`n"
  $html += "  <link rel=`"icon`" href=`"/assets/images/helios_ico.png`" type=`"image/png`">`r`n"
  $html += "  <link rel=`"preconnect`" href=`"https://fonts.googleapis.com`">`r`n"
  $html += "  <link rel=`"preconnect`" href=`"https://fonts.gstatic.com`" crossorigin>`r`n"
  $html += "  <link href=`"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap`" rel=`"stylesheet`">`r`n"
  $html += "  <style>`r`n"
  $html += "    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}`r`n"
  $html += "    :root{--navy:#0b1a35;--yellow:#f5c400;--green:#25d366;--green2:#1ebe5d;--gray:#f4f6f9;--text:#1a2332;--mid:#4a5568;--light:rgba(255,255,255,.8)}`r`n"
  $html += "    html{scroll-behavior:smooth;overflow-x:hidden}body{font-family:'Montserrat',sans-serif;color:var(--text);background:#fff;overflow-x:hidden}`r`n"
  $html += "    .site-topbar{background:#0b1a35;border-bottom:1px solid #1a2e50;padding:0 40px;height:40px;display:flex;align-items:center;justify-content:space-between}`r`n"
  $html += "    .site-topbar a{color:#f5c400;font-size:.72rem;text-decoration:none}.site-topbar span{color:#ccc;font-size:.72rem}`r`n"
  $html += "    .site-nav{background:#0b1a35;padding:0 40px;height:70px;display:flex;align-items:center;justify-content:space-between}`r`n"
  $html += "    .site-nav-logo img{height:48px;object-fit:contain}.site-nav-links{display:flex;gap:32px}`r`n"
  $html += "    .site-nav-links a{color:#fff;text-decoration:none;font-weight:600;font-size:.85rem;transition:color .2s}.site-nav-links a:hover{color:#f5c400}`r`n"
  $html += "    .site-nav-cta{background:#f5c400;color:#0b1a35;font-weight:800;padding:8px 22px;border-radius:8px;text-decoration:none;font-size:.82rem;white-space:nowrap;transition:background .2s}.site-nav-cta:hover{background:#e6b800}`r`n"
  $html += "    .hero{background:linear-gradient(135deg,#00122b 0%,#0b1a35 55%,#0d2250 100%);padding:64px 24px 72px;text-align:center;position:relative;overflow:hidden}`r`n"
  $html += "    .hero::after{content:'';position:absolute;inset:0;background:radial-gradient(ellipse at 50% -10%,rgba(245,196,0,.1) 0%,transparent 65%);pointer-events:none}`r`n"
  $html += "    .hero-inner{max-width:760px;margin:0 auto;position:relative;z-index:1}`r`n"
  $html += "    .hero-badge{display:inline-flex;align-items:center;gap:8px;background:rgba(245,196,0,.12);border:1px solid rgba(245,196,0,.3);color:var(--yellow);font-size:.68rem;font-weight:800;letter-spacing:1.5px;text-transform:uppercase;padding:5px 14px;border-radius:50px;margin-bottom:20px}`r`n"
  $html += "    .hero-badge span{background:var(--yellow);color:var(--navy);padding:2px 8px;border-radius:50px;font-size:.62rem}`r`n"
  $html += "    .hero h1{font-size:clamp(1.7rem,5vw,3rem);font-weight:900;color:#fff;line-height:1.12;margin-bottom:18px}.hero h1 em{color:var(--yellow);font-style:normal}`r`n"
  $html += "    .hero-sub{color:var(--light);font-size:clamp(.88rem,2vw,1.05rem);line-height:1.65;margin-bottom:32px;max-width:580px;margin-left:auto;margin-right:auto}`r`n"
  $html += "    .hero-cta{display:flex;flex-direction:column;align-items:center;gap:12px}`r`n"
  $html += "    .btn-wpp{background:var(--green);color:#fff;padding:16px 36px;border-radius:50px;font-weight:900;font-size:1rem;text-decoration:none;letter-spacing:.3px;transition:transform .2s,box-shadow .2s;box-shadow:0 6px 24px rgba(37,211,102,.45);display:inline-flex;align-items:center;gap:10px}`r`n"
  $html += "    .btn-wpp:hover{transform:translateY(-2px);box-shadow:0 10px 32px rgba(37,211,102,.6)}`r`n"
  $html += "    .hero-note{color:rgba(255,255,255,.45);font-size:.72rem;font-weight:600}`r`n"
  $html += "    .hero-stats{display:flex;justify-content:center;gap:32px;flex-wrap:wrap;margin-top:48px;padding-top:32px;border-top:1px solid rgba(255,255,255,.1)}`r`n"
  $html += "    .hero-stat{text-align:center}.hero-stat .num{font-size:1.6rem;font-weight:900;color:var(--yellow);display:block}.hero-stat .lbl{font-size:.7rem;font-weight:600;color:rgba(255,255,255,.5);text-transform:uppercase;letter-spacing:1px}`r`n"
  $html += "    .urgency-bar{background:var(--yellow);padding:12px 24px;display:flex;align-items:center;justify-content:center;gap:10px;text-align:center}`r`n"
  $html += "    .urgency-bar p{font-size:.82rem;font-weight:800;color:var(--navy)}`r`n"
  $html += "    .section{padding:72px 24px}.section-alt{background:var(--gray)}.container{max-width:1060px;margin:0 auto}`r`n"
  $html += "    .section-head{text-align:center;margin-bottom:48px}.section-head .label{font-size:.65rem;font-weight:800;letter-spacing:2.5px;text-transform:uppercase;color:var(--yellow);display:block;margin-bottom:8px}`r`n"
  $html += "    .section-head h2{font-size:clamp(1.4rem,3vw,2rem);font-weight:900;color:var(--navy)}.section-head p{color:var(--mid);font-size:.9rem;margin-top:10px}`r`n"
  $html += "    .bairros-wrap{display:flex;flex-wrap:wrap;gap:10px;justify-content:center;margin-bottom:16px}`r`n"
  $html += "    .bairro-tag{background:var(--navy);color:var(--yellow);padding:6px 18px;border-radius:50px;font-size:.78rem;font-weight:700}`r`n"
  $html += "    .bairros-note{text-align:center;color:var(--mid);font-size:.82rem}`r`n"
  $html += "    .steps{display:grid;grid-template-columns:repeat(3,1fr);gap:28px}`r`n"
  $html += "    .step-card{background:#fff;border-radius:16px;padding:32px 24px;text-align:center;box-shadow:0 4px 20px rgba(11,26,53,.07);position:relative}`r`n"
  $html += "    .step-card::before{content:attr(data-step);position:absolute;top:-14px;left:50%;transform:translateX(-50%);background:var(--yellow);color:var(--navy);width:28px;height:28px;border-radius:50%;font-size:.8rem;font-weight:900;display:flex;align-items:center;justify-content:center}`r`n"
  $html += "    .step-icon{font-size:2.2rem;margin-bottom:14px}.step-card h3{font-size:.95rem;font-weight:800;color:var(--navy);margin-bottom:8px}.step-card p{font-size:.8rem;color:var(--mid);line-height:1.6}`r`n"
  $html += "    .benefits-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}`r`n"
  $html += "    .benefit{display:flex;align-items:flex-start;gap:14px;background:#fff;border-radius:12px;padding:20px;box-shadow:0 3px 14px rgba(11,26,53,.06);border-left:3px solid var(--yellow)}`r`n"
  $html += "    .benefit-icon{font-size:1.6rem;flex-shrink:0;margin-top:2px}.benefit h4{font-size:.88rem;font-weight:800;color:var(--navy);margin-bottom:4px}.benefit p{font-size:.78rem;color:var(--mid);line-height:1.5}`r`n"
  $html += "    .compare-table{width:100%;border-collapse:collapse;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(11,26,53,.1)}`r`n"
  $html += "    .compare-table th{padding:16px 20px;font-size:.82rem;font-weight:800;text-transform:uppercase;letter-spacing:.5px}`r`n"
  $html += "    .compare-table th:first-child{background:var(--gray);color:var(--mid);text-align:left}.compare-table th.col-seg{background:#e8eaf0;color:#666}.compare-table th.col-helios{background:var(--navy);color:var(--yellow)}`r`n"
  $html += "    .compare-table td{padding:14px 20px;font-size:.85rem;border-bottom:1px solid #eee}.compare-table td:first-child{font-weight:700;color:var(--navy);background:#fafbfc}`r`n"
  $html += "    .compare-table td.col-seg{text-align:center;background:#fff;color:#666}.compare-table td.col-helios{text-align:center;background:rgba(11,26,53,.03);font-weight:700;color:var(--navy)}`r`n"
  $html += "    .check{color:var(--green);font-size:1.1rem;font-weight:900}.cross{color:#e53e3e;font-size:1rem}.compare-table tr:last-child td{border-bottom:none}`r`n"
  $html += "    .testimonials{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}`r`n"
  $html += "    .testimonial{background:#fff;border-radius:16px;padding:24px;box-shadow:0 4px 20px rgba(11,26,53,.07)}`r`n"
  $html += "    .stars{color:var(--yellow);font-size:1rem;margin-bottom:12px;letter-spacing:2px}.testimonial p{font-size:.82rem;color:var(--mid);line-height:1.65;margin-bottom:16px;font-style:italic}`r`n"
  $html += "    .testimonial-author{display:flex;align-items:center;gap:10px}.avatar{width:38px;height:38px;border-radius:50%;background:var(--navy);color:var(--yellow);font-weight:900;font-size:.9rem;display:flex;align-items:center;justify-content:center;flex-shrink:0}`r`n"
  $html += "    .author-name{font-size:.8rem;font-weight:800;color:var(--navy)}.author-city{font-size:.72rem;color:var(--mid)}`r`n"
  $html += "    .faq-list{max-width:720px;margin:0 auto;display:flex;flex-direction:column;gap:12px}`r`n"
  $html += "    .faq-item{background:#fff;border-radius:12px;box-shadow:0 3px 14px rgba(11,26,53,.06);overflow:hidden}`r`n"
  $html += "    .faq-q{padding:18px 20px;font-size:.88rem;font-weight:800;color:var(--navy);cursor:pointer;display:flex;justify-content:space-between;align-items:center;gap:12px;user-select:none}`r`n"
  $html += "    .faq-q::after{content:'+';font-size:1.2rem;font-weight:900;color:var(--yellow);flex-shrink:0;transition:transform .2s}.faq-item.open .faq-q::after{transform:rotate(45deg)}`r`n"
  $html += "    .faq-a{display:none;padding:0 20px 18px;font-size:.82rem;color:var(--mid);line-height:1.7}.faq-item.open .faq-a{display:block}`r`n"
  $html += "    .cta-final{background:linear-gradient(135deg,#00122b 0%,#0b1a35 100%);padding:80px 24px;text-align:center}`r`n"
  $html += "    .cta-final h2{font-size:clamp(1.5rem,4vw,2.4rem);font-weight:900;color:#fff;margin-bottom:12px}.cta-final h2 em{color:var(--yellow);font-style:normal}.cta-final p{color:var(--light);font-size:.92rem;margin-bottom:32px}`r`n"
  $html += "    .lp-footer{background:#060f20;padding:24px;text-align:center}.lp-footer p{color:rgba(255,255,255,.3);font-size:.72rem;line-height:1.7}.lp-footer a{color:rgba(255,255,255,.4);text-decoration:none}.lp-footer a:hover{color:var(--yellow)}`r`n"
  $html += "    .fab{position:fixed;bottom:20px;right:20px;z-index:999;background:var(--green);color:#fff;width:58px;height:58px;border-radius:50%;display:flex;align-items:center;justify-content:center;text-decoration:none;box-shadow:0 6px 24px rgba(37,211,102,.5);transition:transform .2s}.fab:hover{transform:scale(1.1)}`r`n"
  $html += "    .fab-pulse{position:absolute;width:100%;height:100%;border-radius:50%;background:var(--green);opacity:.4;animation:pulse 2s ease-out infinite}`r`n"
  $html += "    @keyframes pulse{0%{transform:scale(1);opacity:.4}100%{transform:scale(1.7);opacity:0}}`r`n"
  $html += "    @media(max-width:768px){.steps{grid-template-columns:1fr;max-width:400px;margin:0 auto}.benefits-grid{grid-template-columns:1fr}.testimonials{grid-template-columns:1fr}.site-nav-links{display:none}.site-topbar span{display:none}.site-topbar,.site-nav{padding:0 16px}}`r`n"
  $html += "    @media(max-width:480px){.hero{padding:48px 20px 56px}.btn-wpp{padding:14px 28px;font-size:.92rem;width:100%;justify-content:center}}`r`n"
  $html += "  </style>`r`n</head>`r`n<body>`r`n"
  $html += "`r`n<div class=`"site-topbar`">`r`n  <a href=`"$wppPhone`" target=`"_blank`" rel=`"noopener noreferrer`">&#128222; (31) 99372-8984</a>`r`n  <span>Atendimento: Seg-Sex 8h-18h | Sab 8h-12h</span>`r`n</div>`r`n"
  $html += "<nav class=`"site-nav`">`r`n  <a class=`"site-nav-logo`" href=`"https://heliosprotecaoveicular.com.br`"><img src=`"/assets/images/logo-helios.png`" alt=`"Helios Protecao Veicular`"></a>`r`n"
  $html += "  <div class=`"site-nav-links`">`r`n    <a href=`"https://heliosprotecaoveicular.com.br`">Home</a>`r`n    <a href=`"https://heliosprotecaoveicular.com.br/#sobre`">Quem Somos</a>`r`n    <a href=`"https://heliosprotecaoveicular.com.br/servicos`">Servicos</a>`r`n    <a href=`"https://heliosprotecaoveicular.com.br/blog/`">Blog</a>`r`n    <a href=`"https://heliosprotecaoveicular.com.br/#contato`">Contato</a>`r`n  </div>`r`n"
  $html += "  <a class=`"site-nav-cta`" href=`"$wppPhone`" target=`"_blank`" rel=`"noopener noreferrer`">Faca sua Cotacao</a>`r`n</nav>`r`n"
  $html += "`r`n<section class=`"hero`">`r`n  <div class=`"hero-inner`">`r`n    <div class=`"hero-badge`"><span>DESTAQUE</span> Protecao ativa desde o 1 dia</div>`r`n"
  $html += "    <h1>Proteja seu veiculo em $name<br><em>sem carencia e sem burocracia</em></h1>`r`n"
  $html += "    <p class=`"hero-sub`">$($c.heroSub)</p>`r`n"
  $html += "    <div class=`"hero-cta`">`r`n      <a class=`"btn-wpp`" href=`"$wppPath`?text=Ola!%20Vi%20o%20anuncio%20e%20quero%20cotacao.`" target=`"_blank`">$svg22 Quero minha cotacao gratis</a>`r`n"
  $html += "      <span class=`"hero-note`">Resposta em minutos - Sem compromisso</span>`r`n    </div>`r`n"
  $html += "    <div class=`"hero-stats`">`r`n      <div class=`"hero-stat`"><span class=`"num`">+1.000</span><span class=`"lbl`">Associados</span></div>`r`n      <div class=`"hero-stat`"><span class=`"num`">24h</span><span class=`"lbl`">Assistencia</span></div>`r`n      <div class=`"hero-stat`"><span class=`"num`">0 dias</span><span class=`"lbl`">de carencia</span></div>`r`n      <div class=`"hero-stat`"><span class=`"num`">100%</span><span class=`"lbl`">Tabela FIPE</span></div>`r`n    </div>`r`n  </div>`r`n</section>`r`n"
  $html += "`r`n<div class=`"urgency-bar`"><p>&#9888; <strong>$($c.urgency)</strong> Nao espere acontecer para se proteger.</p></div>`r`n"
  $html += "`r`n<section class=`"section`">`r`n  <div class=`"container`">`r`n    <div class=`"section-head`"><span class=`"label`">Onde atendemos</span><h2>Atendemos $name e regiao</h2><p>Protecao veicular disponivel em todos os bairros e municipios proximos.</p></div>`r`n"
  $html += "    <div class=`"bairros-wrap`">`r`n$bairrosTags`r`n    </div>`r`n    <p class=`"bairros-note`">Nao encontrou seu bairro? Fale conosco - atendemos toda a $($c.regiao)!</p>`r`n  </div>`r`n</section>`r`n"
  $html += "`r`n<section class=`"section section-alt`">`r`n  <div class=`"container`">`r`n    <div class=`"section-head`"><span class=`"label`">Simples assim</span><h2>Como funciona a protecao Helios</h2><p>Sem letras miudas, sem pegadinhas. Protecao real em 3 passos.</p></div>`r`n"
  $html += "    <div class=`"steps`">`r`n      <div class=`"step-card`" data-step=`"1`"><div class=`"step-icon`">&#128172;</div><h3>Fale conosco</h3><p>Entre em contato pelo WhatsApp. Nosso time responde em minutos e faz a cotacao do seu veiculo gratuitamente.</p></div>`r`n"
  $html += "      <div class=`"step-card`" data-step=`"2`"><div class=`"step-icon`">&#128203;</div><h3>Assine e ative</h3><p>Processo 100% digital. Sem burocracia, sem vistoria demorada. Sua protecao fica ativa no mesmo dia.</p></div>`r`n"
  $html += "      <div class=`"step-card`" data-step=`"3`"><div class=`"step-icon`">&#128737;</div><h3>Dirija tranquilo</h3><p>Com a Helios voce conta com assistencia 24h, carro reserva e cobertura completa onde estiver.</p></div>`r`n    </div>`r`n  </div>`r`n</section>`r`n"
  $html += "`r`n<section class=`"section`">`r`n  <div class=`"container`">`r`n    <div class=`"section-head`"><span class=`"label`">Cobertura completa</span><h2>Tudo que seu veiculo precisa</h2><p>Uma protecao completa pelo preco que cabe no seu bolso.</p></div>`r`n"
  $html += "    <div class=`"benefits-grid`">`r`n      <div class=`"benefit`"><div class=`"benefit-icon`">&#128274;</div><div><h4>Roubo e Furto</h4><p>Cobertura completa com indenizacao pelo valor da tabela FIPE do seu veiculo.</p></div></div>`r`n"
  $html += "      <div class=`"benefit`"><div class=`"benefit-icon`">&#128165;</div><div><h4>Colisao</h4><p>Protecao contra batidas, capotamentos e danos causados por terceiros.</p></div></div>`r`n"
  $html += "      <div class=`"benefit`"><div class=`"benefit-icon`">&#128295;</div><div><h4>Assistencia 24h</h4><p>Guincho, pane seca, chaveiro e socorro mecanico a qualquer hora do dia ou da noite.</p></div></div>`r`n"
  $html += "      <div class=`"benefit`"><div class=`"benefit-icon`">&#128663;</div><div><h4>Carro Reserva</h4><p>Enquanto seu veiculo esta em reparo, voce nao fica na mao. Carro reserva incluido.</p></div></div>`r`n"
  $html += "      <div class=`"benefit`"><div class=`"benefit-icon`">&#129407;</div><div><h4>Cobertura de Vidros</h4><p>Para-brisa, vidros laterais e traseiros cobertos sem franquia adicional.</p></div></div>`r`n"
  $html += "      <div class=`"benefit`"><div class=`"benefit-icon`">&#128225;</div><div><h4>Rastreamento</h4><p>Monitoramento do seu veiculo 24h por dia para recuperacao rapida em caso de roubo.</p></div></div>`r`n    </div>`r`n"
  $html += "    <div style=`"text-align:center;margin-top:40px`"><a class=`"btn-wpp`" href=`"$wppPath`?text=Ola!%20Quero%20saber%20mais.`" target=`"_blank`" style=`"display:inline-flex`">$svg22 Quero essa protecao</a></div>`r`n  </div>`r`n</section>`r`n"
  $html += "`r`n<section class=`"section section-alt`">`r`n  <div class=`"container`">`r`n    <div class=`"section-head`"><span class=`"label`">Compare</span><h2>Helios vs Seguro Tradicional</h2><p>Veja por que cada vez mais motoristas em $name escolhem a protecao veicular.</p></div>`r`n"
  $html += "    <table class=`"compare-table`"><thead><tr><th></th><th class=`"col-seg`">Seguro Tradicional</th><th class=`"col-helios`">Helios Protecao</th></tr></thead><tbody>`r`n"
  $html += "      <tr><td>Sem carencia</td><td class=`"col-seg`"><span class=`"cross`">&#10007;</span> Periodo de carencia</td><td class=`"col-helios`"><span class=`"check`">&#10003;</span> Ativo no 1 dia</td></tr>`r`n"
  $html += "      <tr><td>Preco acessivel</td><td class=`"col-seg`"><span class=`"cross`">&#10007;</span> Alto custo mensal</td><td class=`"col-helios`"><span class=`"check`">&#10003;</span> Ate 70% mais barato</td></tr>`r`n"
  $html += "      <tr><td>Sem vistoria previa</td><td class=`"col-seg`"><span class=`"cross`">&#10007;</span> Vistoria obrigatoria</td><td class=`"col-helios`"><span class=`"check`">&#10003;</span> Sem vistoria</td></tr>`r`n"
  $html += "      <tr><td>Assistencia 24h</td><td class=`"col-seg`"><span class=`"check`">&#10003;</span> Inclusa</td><td class=`"col-helios`"><span class=`"check`">&#10003;</span> Inclusa</td></tr>`r`n"
  $html += "      <tr><td>Carro reserva</td><td class=`"col-seg`"><span class=`"cross`">&#10007;</span> Geralmente extra</td><td class=`"col-helios`"><span class=`"check`">&#10003;</span> Incluso</td></tr>`r`n"
  $html += "      <tr><td>Processo 100% digital</td><td class=`"col-seg`"><span class=`"cross`">&#10007;</span> Muita burocracia</td><td class=`"col-helios`"><span class=`"check`">&#10003;</span> Tudo pelo celular</td></tr>`r`n    </tbody></table>`r`n  </div>`r`n</section>`r`n"
  $html += "`r`n<section class=`"section`">`r`n  <div class=`"container`">`r`n    <div class=`"section-head`"><span class=`"label`">Quem ja protegeu</span><h2>O que nossos associados dizem</h2></div>`r`n"
  $html += "    <div class=`"testimonials`">`r`n"
  $html += "      <div class=`"testimonial`"><div class=`"stars`">&#9733;&#9733;&#9733;&#9733;&#9733;</div><p>`"$($c.t1t)`"</p><div class=`"testimonial-author`"><div class=`"avatar`">$($c.t1i)</div><div><div class=`"author-name`">$($c.t1n)</div><div class=`"author-city`">$($c.t1b)</div></div></div></div>`r`n"
  $html += "      <div class=`"testimonial`"><div class=`"stars`">&#9733;&#9733;&#9733;&#9733;&#9733;</div><p>`"$($c.t2t)`"</p><div class=`"testimonial-author`"><div class=`"avatar`">$($c.t2i)</div><div><div class=`"author-name`">$($c.t2n)</div><div class=`"author-city`">$($c.t2b)</div></div></div></div>`r`n"
  $html += "      <div class=`"testimonial`"><div class=`"stars`">&#9733;&#9733;&#9733;&#9733;&#9733;</div><p>`"$($c.t3t)`"</p><div class=`"testimonial-author`"><div class=`"avatar`">$($c.t3i)</div><div><div class=`"author-name`">$($c.t3n)</div><div class=`"author-city`">$($c.t3b)</div></div></div></div>`r`n"
  $html += "    </div>`r`n  </div>`r`n</section>`r`n"
  $html += "`r`n<section class=`"section section-alt`">`r`n  <div class=`"container`">`r`n    <div class=`"section-head`"><span class=`"label`">Duvidas frequentes</span><h2>Perguntas e respostas</h2></div>`r`n    <div class=`"faq-list`">`r`n"
  $html += "      <div class=`"faq-item`"><div class=`"faq-q`">O que significa sem carencia?</div><div class=`"faq-a`">Significa que sua protecao comeca a valer no mesmo dia da adesao. Diferente do seguro tradicional, que tem um periodo de espera antes de voce poder acionar a cobertura.</div></div>`r`n"
  $html += "      <div class=`"faq-item`"><div class=`"faq-q`">Qual o valor da mensalidade em $name?</div><div class=`"faq-a`">O valor varia de acordo com o modelo, ano e perfil do seu veiculo. Fale conosco pelo WhatsApp e receba sua cotacao gratuita em minutos, sem compromisso.</div></div>`r`n"
  $html += "      <div class=`"faq-item`"><div class=`"faq-q`">Preciso fazer vistoria do veiculo?</div><div class=`"faq-a`">Nao. O processo na Helios e 100% digital e sem necessidade de vistoria previa. Voce assina tudo pelo celular e sua protecao fica ativa no mesmo dia.</div></div>`r`n"
  $html += "      <div class=`"faq-item`"><div class=`"faq-q`">$($c.faqQ)</div><div class=`"faq-a`">$($c.faqA)</div></div>`r`n"
  $html += "      <div class=`"faq-item`"><div class=`"faq-q`">Como funciona em caso de roubo ou colisao?</div><div class=`"faq-a`">Basta entrar em contato com nossa central 24h. Nosso time te orienta sobre todos os passos. O processo e simples e rapido, sem burocracia excessiva.</div></div>`r`n"
  $html += "    </div>`r`n  </div>`r`n</section>`r`n"
  $html += "`r`n<section class=`"cta-final`">`r`n  <div class=`"container`">`r`n    <h2>Seu veiculo protegido <em>ainda hoje</em></h2>`r`n    <p>Sem carencia - Sem vistoria - Processo 100% digital - Resposta em minutos</p>`r`n"
  $html += "    <a class=`"btn-wpp`" href=`"$wppPath`?text=Ola!%20Quero%20minha%20cotacao%20na%20Helios%20agora.`" target=`"_blank`">$svg22 Fazer cotacao gratuita agora</a>`r`n  </div>`r`n</section>`r`n"
  $html += "`r`n<footer class=`"lp-footer`">`r`n  <p>&#169; 2026 Helios Protecao Veicular - $name e $($c.regiao)<br>`r`n  <a href=`"tel:+5531993728984`">(31) 99372-8984</a> - <a href=`"tel:+5531992395859`">(31) 99239-5859</a><br>`r`n  <a href=`"https://heliosprotecaoveicular.com.br`">Site principal</a> - <a href=`"https://heliosprotecaoveicular.com.br/privacidade`">Politica de Privacidade</a></p>`r`n</footer>`r`n"
  $html += "`r`n<a class=`"fab`" href=`"$wppPath`?text=Ola!%20Quero%20cotacao.`" target=`"_blank`" aria-label=`"WhatsApp`"><div class=`"fab-pulse`"></div><svg width=`"26`" height=`"26`" viewBox=`"0 0 24 24`" fill=`"white`"><path d=`"M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z`"/></svg></a>`r`n"
  $html += "`r`n<script>`r`n  document.querySelectorAll('.faq-q').forEach(q=>{q.addEventListener('click',()=>{const item=q.parentElement;const isOpen=item.classList.contains('open');document.querySelectorAll('.faq-item').forEach(i=>i.classList.remove('open'));if(!isOpen)item.classList.add('open')})}))`r`n</script>`r`n</body>`r`n</html>"

  [System.IO.File]::WriteAllText("$dir\index.html", $html, [System.Text.Encoding]::UTF8)
  Write-Host "OK: $slug ($([math]::Round([System.Text.Encoding]::UTF8.GetByteCount($html)/1KB,1)) KB)"
}
Write-Host "Concluido!"
